##### Menu
menu:
  首页: /
  归档: /archives
  关于: /about
## you can create `tags` and `categories` folders in `../source`.
## And create a `index.md` file in each of them.
## set `front-matter`as
## layout: tags (or categories)
## title: tags (or categories)
## ---

#### Widgets
widgets: 
- category
- tagcloud
- blogroll
- links
- weibo
- rss
## provide seven widgets:category,tag,rss,archive,tagcloud,links,weibo,douban


#### RSS 
rss: /atom.xml ## RSS address.

#### Image
imglogo:
  enable: true             ## display image logo true/false.
  src: img/logo.png        ## `.svg` and `.png` are recommended,please put image into the theme folder `/jacman/source/img`.
favicon: img/logo.png   ## size:32px*32px,`.ico` is recommended,please put image into the theme folder `/jacman/source/img`.     
apple_icon: img/logo.png ## size:114px*114px,please put image into the theme folder `/jacman/source/img`.
author_img: img/author.jpg ## size:220px*220px.display author avatar picture.if don't want to display,please don't set this.
banner_img: #img/banner.jpg ## size:1920px*200px+. Banner Picture
### Theme Color 
theme_color:
    theme: '#2ca6cb'    ##the defaut theme color is blue

#### index post is expanding or not 
index:
  expand: true           ## default is unexpanding,so you can only see the short description of each post.
  excerpt_link: Read More  

close_aside: false  #close sidebar in post page if true
mathjax: false      #enable mathjax if true

#### Author information
author:
  intro_line1:  "In my solitude of heart I feel the sigh of this widowed evening veiled with mist and rain."  ## eg: "Hello ,I'm Larry Page in Google."
  intro_line2:  "这寡独的黄昏，幕着雾与雨，我在我心的孤寂里，感觉到它的叹息。"  ## eg: "This is my blog,believe it or not."
  weibo: 3202240184   ## e.g. wuchong1014 or 2176287895 for http://weibo.com/2176287895
  twitter:    ## e.g. wuchong for https://twitter.com/wuchong
  github:     ## e.g. wuchong for https://github.com/wuchong
  facebook:   ## e.g. wuchong for https://facebook.com/wuchong
  douban:     ## e.g. wuchong1014 or your id for https://www.douban.com/people/wuchong1014
  tsina:      ## e.g. 2176287895  Your weibo ID,It will be used in share button.
  email: dyq@hackmz.com     ## e.g. wuchong1014@gmail.com
  google_plus:    ## eg:111190881341800841449 for https://plus.google.com/u/0/111190881341800841449
  stackoverflow:  ##3222790   ##e.g. 3222790 for http://stackoverflow.com/users/3222790/jark
## if you set them, the corresponding  share button will show on the footer

#### Toc
toc:
  article: true   ## show contents in article.
  aside: true     ## show contents in aside.
## you can set both of the value to true of neither of them.
## if you don't want display contents in a specified post,you can modify `front-matter` and add `toc: false`.

#### Links
links:
  Bugs's Blog: http://www.isbugs.com/
  Takwolf's Blog: http://blog.takwolf.com/



duoshuo: 
  enable: true  ## duoshuo.com
  short_name:  mrwheat  ##e.g. wuchong   for duoshuo short name.

disqus:
  enable: false  ## disqus.com
  short_name:    ##e.g. wuchong   for disqus short name.  

#### Share button
jiathis:
  enable: false ## if you use jiathis as your share tool,the built-in share tool won't be display.
  id:    ## e.g. 1889330 your jiathis ID. 
  tsina: ## e.g. 2176287895 Your weibo id,It will be used in share button.

#### Analytics
google_analytics:
  enable: false
  id:        ## e.g. UA-46321946-2 your google analytics ID.
  site:      ## e.g. wuchong.me your google analytics site or set the value as auto.
## You MUST upgrade to Universal Analytics first!
## https://developers.google.com/analytics/devguides/collection/upgrade/?hl=zh_CN
baidu_share:
  enable: true
  color: 4

#### Analytics
baidu_tongji: true

cnzz_tongji:
  enable: false
  siteid:    ## e.g. 1253575964 your cnzz tongji site id

#### Miscellaneous
ShowCustomFont: true  ## you can change custom font in `variable.styl` and `font.styl` which in the theme folder `/jacman/source/css`.
fancybox: true        ## if you use gallery post or want use fancybox please set the value to true.
totop: true           ## if you want to scroll to top in every post set the value to true


#### Custom Search
google_cse: 
  enable: false
  cx:   ## e.g. 018294693190868310296:abnhpuysycw your Custom Search ID.
## https://www.google.com/cse/ 
## To enable the custom search You must create a "search" folder in '/source' and a "index.md" file
## set the 'front-matter' as
## layout: search 
## title: search
## ---
baidu_search:     ## http://zn.baidu.com/
  enable: false
  id:   ## e.g. "783281470518440642"  for your baidu search id
  site: http://zhannei.baidu.com/cse/search  ## your can change to your site instead of the default site
  
tinysou_search:     ## http://tinysou.com/
  enable: false
  id:  ## e.g. "4ac092ad8d749fdc6293" for your tiny search id
